name: pearls
description: "Pearls - personal quote saving app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  sqflite: ^2.4.2+1
  path: ^1.9.1
  uuid: ^4.5.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"